# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matrix_rollsum2 <- function(x, n, margin) {
    .Call('_dbsinglecell_matrix_rollsum2', PACKAGE = 'dbsinglecell', x, n, margin)
}

substr_r <- function(str, n) {
    .Call('_dbsinglecell_substr_r', PACKAGE = 'dbsinglecell', str, n)
}

substr_l <- function(str, n) {
    .Call('_dbsinglecell_substr_l', PACKAGE = 'dbsinglecell', str, n)
}

